### PR TITLE
Tightens consistency

### PR DESCRIPTION
**Pull request by lukecampbell**
- Records will be immediately removed from a folder if they were not
  immediately available in the WAF.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
@lukecampbell , in other words, the datasets currently available in the catalog should mirror the datasets currently available in the various distributed WAFs, right?

**Comment by lukecampbell** [comment]
Yes, that's correct. However, I'm going to add one exception. If the WAF is offline or unreachable, we'll wait 24 hours before removing the records.

https://github.com/ioos/catalog/issues/20

**Comment by rsignell-usgs** [comment]
@lukecampbell.   Awesome.  Sounds like a good compromise. 

Does this close https://github.com/ioos/catalog-harvesting/issues/35 ?

**Comment by lukecampbell** [comment]
I need to update production before I can close #35 at the moment.

**Comment by lukecampbell** [comment]
@rsignell-usgs #35 is now closed.

**Pull request merged**
