### PR TITLE
API

### PR DESCRIPTION
**Pull request by lukecampbell**
py27: commands succeeded

py35: commands succeeded

### CODE REVIEW

**Comment by lukecampbell** [comment]
This is for review only, for the moment. I need to see if it builds in docker and can run.

**Comment by lukecampbell** [comment]
Ok, now the docker file is updated, this is in a good place I think.

**Comment by lukecampbell** [comment]
@benjwadams

**Comment by benjwadams** [comment]
No ports exposed in Dockerfile or docker-compose.yml.  Is this intentional?

**Pull request merged**
