### PR TITLE
WAF link fixes

### PR DESCRIPTION
**Pull request by benjwadams**
Fixes some bugs mostly related to harvesting of ERDDAP 1.82 WAF harvesting

### CODE REVIEW

**Comment by benjwadams** [comment]
Related to https://github.com/ioos/catalog/issues/64 .
Needs review from someone else (whom?) working on catalog.

**Comment by rsignell-usgs** [comment]
I would hope that someone from @axiom-data-science could take a look here since they apparently have customized the ERDDAP services deployed for CENCOOS and SECOORA, and would have some insight as to why CENCOOS is working and SECOORA is not working (https://github.com/ioos/catalog/issues/64#issuecomment-410054048)

**Comment by benjwadams** [comment]
Parent/referring issue should describe the error condition we're running into.  I ran locally with these changes and was able to get things harvested properly.

**Comment by mwengren** [comment]
@benjwadams If you think it works via your local testing, lets go ahead and merge and run on the live Registry.  There are only a few ERDDAP WAF sources in there, so if there happens to be an issue it will not be a back breaker.

**Comment by kwilcox** [comment]
@rsignell-usgs There is no difference between the CeNCOOS and SECOORA ERDDAP servers.

I harvest all of the WAFS defined in the registry fine (including ERDDAP):

```bash
for x in $(curl 'https://registry.ioos.us/api/v1/Harvests' | jq -r '.data[].url'); do
    wget -r -np -A "*.xml" $x
done
```

**Comment by rsignell-usgs** [comment]
@kwilcox , okay, thanks!    So @benjwadams , can't we just look at what's happening with CENCOOS and do the same for SECOORA?

**Comment by benjwadams** [comment]
@rsignell-usgs , the code merged in here has been moved to production and now is working again.  Either the WAF or ERDDAP-WAF harvest types should work for ERDDAP 1.82 now.  The previous errors were related to fetching `<a>` elements that had no href and attempting to call a string method on Python `None` type, which led to an unhandled exception, but are now tested for.

**Pull request merged**
