### PR TITLE
Uses stricter synchronization

### PR DESCRIPTION
**Pull request by lukecampbell**
- Delete all records from a harvest collection before downloading XMLs. 
- Delete all XML files older than 1 day.

### CODE REVIEW

**Comment by lukecampbell** [comment]
@mwengren The more I think about this, the more I think we should go with stricter synchronization. Before we had loose consistency which means that even if a data provider shut down THREDDS and deleted all their data, we would still have a dataset in NGDC for that old dataset unless we initiated a "force cleanout". 

Well, we had to do cleanouts frequently and often, which makes me think as we go forward, it might be more prudent to have a stricter consistency model. We will harvest every day and sometimes more frequently, and if your XML document is missing for more than a day it will disappear from the system.

This stricter consistency model eliminates the need for us to do manual cleanouts. And it allows us, as developers, to make better assumptions about consistency between data-providers, the registry and CKAN.

**Comment by lukecampbell** [comment]
Also, I'm thinking about how to directly link a registry harvest that automatically kicks off a CKAN harvest for even tighter consistency.

**Comment by mwengren** [comment]
@lukecampbell Sorry i didn't comment on this sooner.   Anyway, I think it makes sense, and since it's been merged already probably moot.  I would worry about WAF harvesting problems causing apparent data service outages (esp since you said some of the WAF web hosts are slow or sometimes unresponsive), but I think it makes sense to use this approach at the outset, and if we need to adjust the tolerance for keeping XML metadata files longer than a day we can do that.  We'll just have to monitor how things are working and make changes as necessary, or inform the RA providers running the WAF server(s) of the issues on their side - this would be a good way to detect those.  If adding this helps with implementing tightly coupled harvesting in CKAN as well, then I'm all for it.   Thanks for the heads up.

**Comment by lukecampbell** [comment]
Yeah it's a game of fine balance. I feel like I've run into instances where data providers moved a dataset or archived it and then removed it from production hosting, a lot, but our previous catalog was not able to synchronize with that well.

**Pull request merged**
